[package]
name = "castep-seeding-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.95", features = ["full"] }

[dev-dependencies]
castep-seeding = {path="../"}

[lib]
proc-macro=true
