[package]
name = "castep-seeding"
version = "0.1.0"
edition = "2021"

[dependencies]
castep-periodic-table = "0.5.2"
castep-cell-io = {git = "https://github.com/TonyWu20/castep-cell-io.git", branch = "dev"}
glob = "0.3.1"
thiserror = "2.0.8"

[features]
default = ["template"]
template =[]
